zalando-incubator/atlas-js-core

README.md
package.json

link to AtlasSDK Reference Documentation added. URL to git repo fixed
ISSUES CLOSED: #3

docs: link to AtlasSDK Reference Documentation

---

.travis.yml
README.md
codecov.yml
package.json

Codecov setup with Codecov README badge added
ISSUES CLOSED: #2

feat: codecov setup

---

.travis.yml
package.json

gh-pages-travis setup is fixed; wrong package version fixed; Travis CI build steps are defined more
precisely
#4

ci: gh-pages setup for Travis CI

---

CONTRIBUTING.md
README.md

README and CONTRIBUTING updated with info about Local Development
#4, #9

docs: README fix

---

src/api/atlas_sdk_client.js

#13 Added switch to Location header if present

#13: Added switch to Location header if present

---

src/models/__tests__/catalog_service_models_test.js
src/models/catalog_api_models.js

Reviews are added to the Catalog API
#37

feat: Add reviews to the Catalog API

---

src/models/__tests__/catalog_service_models_test.js
src/models/catalog_api_models.js

Article Reviews is an optional field
#39

fix: Article Reviews are optional

---

.zappr.yml

added zappr.yml

---

.zappr.yml

chore(zappr conf): changed zappr conf to correct values

---

.zappr.yml

Fix zappr again

---

src/models/__tests__/catalog_service_models_test.js
src/models/catalog_api_models.js

feat(Changes to Catalog API): Breaking Changes to Catalog API

feat(Changes to Catalog API): Changes to Catalog API

---

package.json
src/api/__tests__/config_service_tests.js
src/api/__tests__/data/config_service_response.json
src/api/atlas_sdk_client.js
src/models/config_models.js

#53 Add  header, extend configuration

---

package.json

build: Bump 1.4.1 version

---

src/api/__tests__/config_service_tests.js
src/api/atlas_sdk_client.js

We need to have a method to get country code based on sales_channel
#60

fix: Add getCountryCode() method

---

src/api/__tests__/config_service_tests.js
src/api/__tests__/data/config_service_response.json
src/api/atlas_sdk_client.js
src/models/config_models.js

Reco conf now is taken from list, as config api provides
closes #62

fix(CODE): fix wrong reco conf

---

src/api/__tests__/data/catalog_service_response.json
src/models/__tests__/catalog_service_models_test.js
src/models/catalog_api_models.js

#64 feat(Handle media item type): Handle media item type Image 360, vide…o, etc..

feat(Handle media item type): Handle media item type

---

src/api/__tests__/config_service_tests.js
src/api/atlas_sdk_client.js

#66 Added getConfig to return clientId and SalesChannel

#66 - fix: Added getConfig

---

src/api/__tests__/data/catalog_service_response.json
src/models/__tests__/catalog_service_models_test.js
src/models/catalog_api_models.js

Issue 71 - Add Detail URL Support

---

package.json

Add Detail URL Support. Bump new version.
#71

fix: Add Detail URL Support

---

package.json

use same version as https://www.npmjs.com/package/atlas-sdk-core

chore(project): bump package.json version

---

LICENSE

#69: Since we're bundling isomorphic-fetch into our final bundle we need to add a LICENSE from  isomorphic-fetch  to ours.

#69: Update LICENSE

---

README.md
SECURITY.md

Adding additional informations to comply to OSS guidelines

Update oss doc

---

src/api/__tests__/data/recommendation_service_response_for_brand.json
src/api/__tests__/recommendation_models_tests.js
src/api/atlas_sdk_client.js

feat(Recos): Type param for getRecommendations() added
Closes #115

feat(Recos): Type param for getRecommendations() added

---

src/models/__tests__/address_model_test.js
src/models/address_models.js

feat(models): make memberId field on pickup point optional

---

README.md
package-lock.json
src/api/__tests__/checkout_api_service_tests.js
src/api/atlas_sdk_client.js

fix(CustomerToken): #123 - Added token authorization to customer endpoint

fix(CustomerToken): #123 - Added token authorization to customer endpoint

---

src/api/atlas_sdk_client.js

Add Authorization Token in Checkout API Calls
Fixes #125

fix: add Authorization Token in Checkout API Calls

---

src/api/__tests__/data/config_service_response.json
src/api/atlas_sdk_client.js

Added test for API url
Fixes #127

#127 - fix: added tests for API url

---

ISSUE_TEMPLATE.md
src/api/atlas_sdk_client.js

fix(Fetch): typeMismatchError fix for Windows Edge
Closes #132

fix(Fetch): typeMismatchError fix for Windows Edge

---

package-lock.json
package.json
src/api/atlas_sdk_client.js

fix(Cart): add X-UI header to all cart operations
Closes #136

fix(Cart): add X-UI header to all cart operations

---

package-lock.json
package.json
src/api/atlas_sdk_client.js

Reverts zalando-incubator/atlas-js-core#137 because of changes in API

Revert "fix(Cart): add X-UI header to all cart operations"

---

README.md
src/api/atlas_sdk_client.js

fix(Cart): degrade version, docs update
Closes #136

fix(Cart): degrade version, docs update

---

src/index.js

add simple cache

---

README.md
package.json

fix(version): new version

---

src/index.js

cache returns a promise noe
none

fix(cache): return promise

---

src/index.js

#149 fix cache

---

src/api/atlas_sdk_client.js

fix(logging): #153 - removed console logging for errors

fix(logging): #153 - removed console logging for errors

---

src/api/atlas_sdk_client.js

fix(scalyr): #153 - sanitize error token

fix(scalyr): #153 - sanitize error token

---

package.json

fix(Node):  fix engines in package.json
Closes #160

fix(Node):  fix engines in package.json

---

src/api/atlas_sdk_client.js

fix(scalyr): #153 - added status response in error

fix(scalyr): #153 - added status response in error

---

src/api/atlas_sdk_client.js

fix(scalyr): #153 - fixed empty headers

fix(scalyr): #153 - fixed empty headers

---

src/api/atlas_sdk_client.js

fix(scalyr): #153 - revert error response due to bug

fix(scalyr): #153 - revert error response due to bug

---

package.json

build(SemanticRelease): Fix semantic-release config
Related to #131

build(SemanticRelease): Fix semantic-release config

---

.travis.yml
package.json

build(SemanticRelease): Updated Travis config for new SemanticRelease
Related to #131

build(SemanticRelease): Updated Travis config for new SemanticRelease

---

src/api/atlas_sdk_client.js

fix(atlas_sdk_client): remove JSON.stringify from createGuestOrder

---

README.md
src/api/atlas_sdk_client.js

feat(refactorPutcheckoutcart): refactor method to accept custom headers

---

package.json
src/api/atlas_sdk_client.js

failsafe check for filters when value is provided but undefined
closes #194

fix(getRecommendations): failsafe for filters

---

README.md
package.json

revert version update in package.json as semantic-version is complaining
about same version
related to #205 #204

docs(package): revert package.json version update

---

src/api/atlas_sdk_client.js

feat(recos): add reco_location param for getRecommendations

---

.babelrc
README.md
package-lock.json
package.json
src/api/__tests__/catalog_service_tests.js
src/api/__tests__/data/catalog_service_get_article_response.json
src/api/__tests__/data/catalog_service_get_articles_response.json
src/models/__tests__/catalog_service_models_test.js
src/models/__tests__/customer_model_test.js
src/models/catalog_api_models.js
webpack.config.js

feat(article): forward silhouette from article response

---

package.json
src/api/__tests__/catalog_families_tests.js
src/api/__tests__/data/catalog_families_response.json
src/api/__tests__/data/recommendation_service_response.json
src/api/__tests__/data/recommendation_service_response_for_brand_filter.json
src/api/__tests__/recommendation_tests.js
src/api/atlas_sdk_client.js
src/models/__tests__/recommendation_models_tests.js
src/models/catalog_api_models.js
src/models/recommendation_models.js

Forward productGroup and lowestPrice fields

---

package.json

chore(package.json): pump down version

---

package.json

related to https://github.com/semantic-release/semantic-release/issues/1077

update(package.json): pump version

---

package.json
webpack.config.base.js

fix(babelConfig): restore babel config used by webpack web

---

package.json

fix(versioning): revert version bump
